// Manual mock for utils/config to avoid import.meta issues in Jest

const mockDefaults: Record<string, string> = {
  autosend_from_mic: 'true',
  wake_word_enabled: 'false',
  wake_word: 'Hello',
  time_before_idle_sec: '20',
  debug_gfx: 'false',
  use_webgpu: 'false',
  mtoon_debug_mode: 'none',
  mtoon_material_type: 'mtoon',
  bg_color: '#000000',
  bg_url: '/bg/bg-room2.jpg',
  vrm_url: '/vrm/AvatarSample_A.vrm',
  vrm_hash: '',
  vrm_save_type: 'web',
  youtube_videoid: '',
  animation_url: '/animations/idle_loop.vrma',
  animation_procedural: 'false',
  chatbot_backend: 'chatgpt',
  arbius_llm_model_id: 'default',
  openai_apikey: 'default',
  openai_url: 'https://api-01.heyamica.com',
  openai_model: 'gpt-4o',
  llamacpp_url: 'http://127.0.0.1:8080',
  llamacpp_stop_sequence: '(End)||[END]||Note||***||You:||User:||</s>',
  ollama_url: 'http://localhost:11434',
  ollama_model: 'llama2',
  koboldai_url: 'http://localhost:5001',
  koboldai_use_extra: 'false',
  koboldai_stop_sequence: '(End)||[END]||Note||***||You:||User:||</s>',
  tts_muted: 'false',
  tts_backend: 'openai_tts',
  stt_backend: 'whisper_openai',
  vision_backend: 'vision_openai',
  vision_system_prompt: 'You are a friendly human named Amica. Describe the image in detail. Let\'s start the conversation.',
  vision_openai_apikey: 'default',
  vision_openai_url: 'https://api-01.heyamica.com',
  vision_openai_model: 'gpt-4-vision-preview',
  vision_llamacpp_url: 'http://127.0.0.1:8081',
  vision_ollama_url: 'http://localhost:11434',
  vision_ollama_model: 'llava',
  whispercpp_url: 'http://localhost:8080',
  openai_whisper_apikey: 'default',
  openai_whisper_url: 'https://api-01.heyamica.com',
  openai_whisper_model: 'whisper-1',
  openai_tts_apikey: 'default',
  openai_tts_url: 'https://api-01.heyamica.com',
  openai_tts_model: 'tts-1',
  openai_tts_voice: 'nova',
  rvc_url: 'http://localhost:8001/voice2voice',
  rvc_enabled: 'false',
  rvc_model_name: 'model_name.pth',
  rvc_f0_upkey: '0',
  rvc_f0_method: 'pm',
  rvc_index_path: 'none',
  rvc_index_rate: '0.66',
  rvc_filter_radius: '3',
  rvc_resample_sr: '0',
  rvc_rms_mix_rate: '1',
  rvc_protect: '0.33',
  coquiLocal_url: 'http://localhost:5002',
  coquiLocal_voiceid: 'p240',
  localXTTS_url: 'http://127.0.0.1:7851/api/tts-generate',
  piper_url: 'https://i-love-amica.com:5000/tts',
  elevenlabs_apikey: '',
  elevenlabs_voiceid: '21m00Tcm4TlvDq8ikWAM',
  elevenlabs_model: 'eleven_monolingual_v1',
  speecht5_speaker_embedding_url: '/speecht5_speaker_embeddings/cmu_us_slt_arctic-wav-arctic_a0001.bin',
  coqui_apikey: '',
  coqui_voice_id: '71c6c3eb-98ca-4a05-8d6b-f8c2b5f9f3a3',
  name: 'Amica',
  system_prompt: 'You are a helpful AI assistant.',
  scenario_url: '/scenarios/test1.js',
};

export function config(key: string): string {
  return mockDefaults[key] || '';
}

export function setConfig(key: string, value: string): void {
  mockDefaults[key] = value;
}

export function getAllConfig(): Record<string, string> {
  return { ...mockDefaults };
}
