version: '3.8'

services:
  piper:
    image: rhasspy/wyoming-piper:latest
    container_name: amica-piper
    ports:
      - "${PIPER_PORT:-10200}:10200"
    volumes:
      - piper-data:/data
    command: ["--voice", "${PIPER_VOICE:-en_US-lessac-medium}"]
    healthcheck:
      test: ["CMD-SHELL", "echo 'test' | nc -z localhost 10200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  piper-data:
