version: 2
updates:
  # Contracts dependencies
  - package-ecosystem: "npm"
    directory: "/contracts"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Amica dependencies
  - package-ecosystem: "npm"
    directory: "/amica"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Subdomain service dependencies
  - package-ecosystem: "npm"
    directory: "/subdomain-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Subsquid dependencies
  - package-ecosystem: "npm"
    directory: "/subsquid"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Website dependencies
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
