version: '3.8'

services:
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: amica-whisper
    ports:
      - "${WHISPER_PORT:-9000}:9000"
    environment:
      - ASR_MODEL=${WHISPER_MODEL:-base}
      - ASR_ENGINE=faster_whisper
      - ASR_LANGUAGE=${WHISPER_LANGUAGE:-auto}
      - ASR_THREADS=${WHISPER_THREADS:-4}
    volumes:
      - whisper-models:/root/.cache/whisper
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  whisper-models:
