[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'forge-test'
cache_path  = 'cache_forge'
viaIR = true
remappings = [
    'forge-std/=lib/forge-std/src/',
    'v4-core/=node_modules/@uniswap/v4-core/',
    'v4-periphery/=node_modules/@uniswap/v4-periphery/',
    '@openzeppelin/=node_modules/@openzeppelin/'
]
