[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'cache_forge'
viaIR = true
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
evm_version = "cancun"
remappings = [
    'forge-std/=lib/forge-std/src/',
    'v4-core/=node_modules/@uniswap/v4-core/',
    'v4-periphery/=node_modules/@uniswap/v4-periphery/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'openzeppelin-foundry-upgrades/=node_modules/@openzeppelin/foundry-upgrades/src/'
]
