[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.26'
test = 'test'
cache_path  = 'cache_forge'
viaIR = false
# viaIR = true # causes ICE
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
evm_version = "cancun"
optimizer = true
optimizer_runs = 1

[fmt]
line_length = 80
