version: "3"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: amica_indexer
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
