version: "3"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: amica_indexer
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  processor:
    build: .
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=amica_indexer
      - DB_USER=postgres
      - DB_PASS=postgres
      - RPC_BASE_HTTP=${RPC_BASE_HTTP:-https://mainnet.base.org}
      - PROCESSOR_PROMETHEUS_PORT=3000
    command: ["node", "-r", "dotenv/config", "lib/main.js"]
    ports:
      - "3000:3000"
    profiles:
      - full

  graphql:
    build: .
    depends_on:
      - db
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=amica_indexer
      - DB_USER=postgres
      - DB_PASS=postgres
      - GQL_PORT=4000
    command: ["npx", "squid-graphql-server"]
    ports:
      - "4000:4000"
    profiles:
      - full
