name: Coverage

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [contracts, amica, subdomain-service, subsquid]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Install Foundry
        if: matrix.package == 'contracts'
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: cd ${{ matrix.package }} && npm ci

      - name: Compile contracts
        if: matrix.package == 'contracts'
        run: cd ${{ matrix.package }} && forge build

      - name: Run coverage
        run: cd ${{ matrix.package }} && npm run test:coverage

      - name: Determine lcov path
        id: lcov-path
        run: |
          if [ -f "${{ matrix.package }}/lcov.info" ]; then
            echo "path=${{ matrix.package }}/lcov.info" >> $GITHUB_OUTPUT
          elif [ -f "${{ matrix.package }}/coverage/lcov.info" ]; then
            echo "path=${{ matrix.package }}/coverage/lcov.info" >> $GITHUB_OUTPUT
          else
            echo "path=${{ matrix.package }}/lcov.info" >> $GITHUB_OUTPUT
          fi

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{ matrix.package }}
          parallel: true
          file: ${{ steps.lcov-path.outputs.path }}
        continue-on-error: true

  finish:
    needs: coverage
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          carryforward: true

  # Non-coverage CI jobs
  website:
    name: Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: website/package-lock.json

      - name: Install dependencies
        run: cd website && npm ci

      - name: Build website
        run: cd website && npm run build

      - name: Lint check
        run: cd website && npm run lint

  subsquid:
    name: Subsquid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: subsquid/package-lock.json

      - name: Install dependencies
        run: cd subsquid && npm ci

      - name: Build subsquid
        run: cd subsquid && npm run build

  subdomain-service:
    name: Subdomain Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: subdomain-service/package-lock.json

      - name: Install dependencies
        run: cd subdomain-service && npm ci

      - name: Build subdomain service
        run: cd subdomain-service && npm run build
